-- Generated by Oracle SQL Developer Data Modeler 21.2.0.183.1957
--   at:        2021-12-18 21:10:53 EET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE cursanti (
    id_cursant NUMBER(10) NOT NULL,
    nume       VARCHAR2(40) NOT NULL,
    varsta     NUMBER(2) NOT NULL,
    ocupatie   VARCHAR2(10)
);

ALTER TABLE cursanti
    ADD CONSTRAINT cursanti_nume_ck CHECK ( length(nume) > 1
                                            AND REGEXP_LIKE ( nume,
                                                              '[A-Za-z ]+' ) );

ALTER TABLE cursanti
    ADD CONSTRAINT cursanti_varsta_ck CHECK ( varsta BETWEEN 14 AND 22 );

ALTER TABLE cursanti
    ADD CONSTRAINT cursanti_ocupatie_ck CHECK ( ocupatie IN ( 'elev', 'student' ) );

ALTER TABLE cursanti ADD CONSTRAINT cursanti_pk PRIMARY KEY ( id_cursant );

CREATE TABLE cursuri (
    id_curs        NUMBER(10) NOT NULL,
    durata         NUMBER(2) NOT NULL,
    max_locuri     NUMBER(2) NOT NULL,
    nr_inscrisi    NUMBER(2) NOT NULL,
    instrument     VARCHAR2(30) NOT NULL,
    taxa_inscriere NUMBER(10) NOT NULL,
    id_profesor    NUMBER(10) NOT NULL
);

ALTER TABLE cursuri ADD CONSTRAINT cursuri_durata_ck CHECK ( durata > 0 );

ALTER TABLE cursuri ADD CONSTRAINT cursuri_maxlocuri_ck CHECK ( max_locuri > 0 );

ALTER TABLE cursuri ADD CONSTRAINT cursuri_nrinscrisi_ck CHECK ( nr_inscrisi >= 0 );

ALTER TABLE cursuri ADD CONSTRAINT cursuri_taxainscriere_ck CHECK ( taxa_inscriere > 0 );

ALTER TABLE cursuri ADD CONSTRAINT cursuri_pk PRIMARY KEY ( id_curs );

CREATE TABLE detalii_cursanti (
    gen        CHAR(1),
    email      VARCHAR2(40),
    id_cursant NUMBER(10) NOT NULL
);

ALTER TABLE detalii_cursanti
    ADD CONSTRAINT detaliicursanti_gen_ck CHECK ( gen IN ( 'F', 'M' ) );

ALTER TABLE detalii_cursanti
    ADD CONSTRAINT detaliicursanti_email_ck CHECK ( REGEXP_LIKE ( email,
                                                                  '[a-z0-9._%-]+@[a-z0-9._%-]+\.[a-z]{2,4}' ) );

ALTER TABLE detalii_cursanti ADD CONSTRAINT detalii_cursanti_pkv2 PRIMARY KEY ( id_cursant );

ALTER TABLE detalii_cursanti ADD CONSTRAINT detaliicursanti_email_uk UNIQUE ( email );

CREATE TABLE fisa_inscriere (
    data_inscriere DATE NOT NULL,
    nota_evaluare  NUMBER(2),
    id_cursant     NUMBER(10) NOT NULL,
    id_curs        NUMBER(10) NOT NULL
);

ALTER TABLE fisa_inscriere
    ADD CONSTRAINT fisainscriere_notaevaluare_ck CHECK ( nota_evaluare BETWEEN 3 AND 10 );

CREATE TABLE profesori (
    id_profesor NUMBER(10) NOT NULL,
    nume        VARCHAR2(50) NOT NULL
);

ALTER TABLE profesori
    ADD CONSTRAINT profesori_nume_ck CHECK ( length(nume) > 1
                                             AND REGEXP_LIKE ( nume,
                                                               '[A-Za-z ]+' ) );

ALTER TABLE profesori ADD CONSTRAINT profesori_pk PRIMARY KEY ( id_profesor );

CREATE TABLE program (
    zi      VARCHAR2(20) NOT NULL,
    ora     DATE NOT NULL,
    sala    NUMBER(3) NOT NULL,
    id_curs NUMBER(10) NOT NULL
);

ALTER TABLE program
    ADD CONSTRAINT program_zi_ck CHECK ( zi IN ( 'joi', 'luni', 'marti', 'miercuri', 'vineri' ) );

ALTER TABLE program
    ADD CONSTRAINT program_sala_ck CHECK ( sala BETWEEN 100 AND 120
                                           OR sala BETWEEN 200 AND 220 );

ALTER TABLE program
    ADD CONSTRAINT program_pk PRIMARY KEY ( zi,
                                            ora,
                                            sala );

ALTER TABLE detalii_cursanti
    ADD CONSTRAINT cursanti_detaliicursanti_fkv1 FOREIGN KEY ( id_cursant )
        REFERENCES cursanti ( id_cursant );

ALTER TABLE fisa_inscriere
    ADD CONSTRAINT cursanti_fisainscriere_fk FOREIGN KEY ( id_cursant )
        REFERENCES cursanti ( id_cursant );

ALTER TABLE fisa_inscriere
    ADD CONSTRAINT cursuri_fisainscriere_fk FOREIGN KEY ( id_curs )
        REFERENCES cursuri ( id_curs );

ALTER TABLE program
    ADD CONSTRAINT cursuri_program_fk FOREIGN KEY ( id_curs )
        REFERENCES cursuri ( id_curs );

ALTER TABLE cursuri
    ADD CONSTRAINT profesori_cursuri_fk FOREIGN KEY ( id_profesor )
        REFERENCES profesori ( id_profesor );

CREATE SEQUENCE cursanti_id_cursant_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER cursanti_id_cursant_trg BEFORE
    INSERT ON cursanti
    FOR EACH ROW
    WHEN ( new.id_cursant IS NULL )
BEGIN
    :new.id_cursant := cursanti_id_cursant_seq.nextval;
END;
/

CREATE SEQUENCE cursuri_id_curs_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER cursuri_id_curs_trg BEFORE
    INSERT ON cursuri
    FOR EACH ROW
    WHEN ( new.id_curs IS NULL )
BEGIN
    :new.id_curs := cursuri_id_curs_seq.nextval;
END;
/

CREATE SEQUENCE profesori_id_profesor_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER profesori_id_profesor_trg BEFORE
    INSERT ON profesori
    FOR EACH ROW
    WHEN ( new.id_profesor IS NULL )
BEGIN
    :new.id_profesor := profesori_id_profesor_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             24
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           3
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          3
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
